/* open-eyes C ABI — generated by cbindgen. DO NOT EDIT. */

#ifndef OPEN_EYES_H
#define OPEN_EYES_H

/* Auto-generated by cbindgen. Changes will be overwritten. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event types emitted by the pipeline.
 */
typedef enum OEEventType {
  /**
   * Optical flow detected significant motion
   */
  MOTION = 0,
  /**
   * Camera drift detected (recalibration may be needed)
   */
  CAMERA_DRIFT = 1,
  /**
   * New entity entered scene
   */
  ENTITY_ENTERED = 2,
  /**
   * Entity left scene
   */
  ENTITY_LEFT = 3,
  /**
   * Entity crossed zone boundary
   */
  ZONE_CROSSING = 4,
  /**
   * New plane detected
   */
  PLANE_DETECTED = 5,
  /**
   * Pipeline error
   */
  ERROR = 255,
} OEEventType;

/**
 * Pixel format of incoming camera frames.
 */
typedef enum OEPixelFormat {
  /**
   * BGRA 8-bit per channel (iOS AVCaptureSession default)
   */
  BGRA8 = 0,
  /**
   * YUV 4:2:0 planar (Android Camera2 / CameraX)
   */
  YUV420 = 1,
  /**
   * RGB 8-bit per channel
   */
  RGB8 = 2,
  /**
   * Grayscale 8-bit
   */
  GRAY8 = 3,
} OEPixelFormat;

/**
 * Internal engine state. Opaque to callers — they get a raw pointer.
 */
typedef struct OEEngine OEEngine;

/**
 * Configuration for pipeline creation.
 */
typedef struct OEConfig {
  /**
   * Maximum cameras to support
   */
  uint32_t max_cameras;
  /**
   * Enable optical flow (Tier 1 — every frame)
   */
  bool enable_flow;
  /**
   * Enable feature tracking
   */
  bool enable_features;
  /**
   * Enable ML inference (normals, semantic — requires models)
   */
  bool enable_ml;
  /**
   * Target processing FPS (0 = unlimited)
   */
  uint32_t target_fps;
} OEConfig;

/**
 * Pipeline event delivered via callback.
 */
typedef struct OEEvent {
  enum OEEventType event_type;
  uint32_t camera_id;
  uint64_t entity_id;
  /**
   * Event-specific scalar (e.g. motion magnitude, drift amount)
   */
  float value;
  float position[3];
  /**
   * Monotonic timestamp (seconds)
   */
  double timestamp;
} OEEvent;

/**
 * Create a new open-eyes engine with default configuration.
 * Returns an opaque pointer. Caller owns it, must call oe_destroy.
 */
struct OEEngine *oe_create(void);

/**
 * Create with custom configuration.
 */
struct OEEngine *oe_create_with_config(struct OEConfig config);

/**
 * Destroy the engine. Must be called exactly once per oe_create.
 *
 * # Safety
 * `engine` must be a valid pointer from oe_create, not yet destroyed.
 */
void oe_destroy(struct OEEngine *engine);

/**
 * Push a raw camera frame into the pipeline.
 *
 * Called directly from the native camera callback (AVCaptureOutput / CameraX).
 * The pixel data is read synchronously — caller can reuse the buffer after return.
 * All GPU filter work is dispatched lazily from here.
 *
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * - `engine` must be valid
 * - `data` must point to `len` readable bytes
 */
int32_t oe_push_frame(struct OEEngine *engine,
                      uint32_t camera_id,
                      const uint8_t *data,
                      uintptr_t len,
                      uint32_t width,
                      uint32_t height,
                      enum OEPixelFormat format,
                      int32_t rotation);

/**
 * Set camera pose from ARKit/ARCore.
 * `transform` is a 4x4 column-major float matrix (16 floats).
 *
 * # Safety
 * - `engine` must be valid
 * - `transform` must point to 16 readable f32 values
 */
int32_t oe_set_camera_pose(struct OEEngine *engine, uint32_t camera_id, const float *transform);

/**
 * Get the current motion magnitude (0.0 = static, higher = more motion).
 * Cheapest possible query — single float, no allocation.
 */
float oe_get_motion(const struct OEEngine *engine);

/**
 * Get total frames processed.
 */
uint64_t oe_get_frame_count(const struct OEEngine *engine);

/**
 * Poll pending events. Calls `callback` for each event, then drains the buffer.
 * The OEEvent pointer is valid only for the duration of the callback.
 *
 * # Safety
 * - `engine` must be valid
 * - `callback` must be a valid function pointer
 */
int32_t oe_poll_events(const struct OEEngine *engine, void (*callback)(const struct OEEvent*));

/**
 * Set camera intrinsics for a specific camera.
 * Must be called before pushing frames for best results.
 *
 * # Safety
 * - `engine` must be valid
 */
int32_t oe_set_intrinsics(struct OEEngine *engine,
                          uint32_t camera_id,
                          double fx,
                          double fy,
                          double cx,
                          double cy,
                          uint32_t width,
                          uint32_t height,
                          double k1,
                          double k2,
                          double k3);

#endif  /* OPEN_EYES_H */
